#Persistent
+F1:: ; INICIA SCRITP (SHIFT + F1)
SetTimer, ROTINA, 0 ; ROTINA A CADA X SEGUNDONS
Return

ROTINA:
CoordMode, Pixel, Screen ;AJUSTA COORDENADAS INFORMADAS AO PIXELSEARCH SEJA RELATIVA A TELA INTEIRA .
PixelSearch, PosX, PosY, 0, 0, 3000, 3000, 0x4C44CA, 1, FAST RGB ; HEXADECIMAL DO BOSS E AREA DE BUSCA 3000x3000

if (ErrorLevel = 0) ; CONDIÇÃO PARA EXECUTAR A FUNÇÃO
{	
	Funcao_Exemplo(PosX, PosY) ; CHAMA A FUNÇÃO PASSAND COMO PARAMETROS %POSICAO_X%, %POSICAO_Y%
Else
{
	send, {f4} ;TECLA DA ASA DE MOSCA
}
Return

Funcao_Exemplo(Posicao_X, Posicao_Y)
{
	CoordMode, Mouse, Screen ; AJUSTA MOUSEMOVE A TELA INTEIRA DO COMPUTADOR
	MouseMove, %Posicao_X%, %Posicao_Y% ; MOVE O MOUSE PARA A COORDENADA SETTADA
	Pause ;PAUSA AO ACHAR O BOSS/PIXEL
	
}
^u::Pause ; PARA SCRIPT
Return
